repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.271"
    hooks:
      - id: ruff
        entry: ruff check --fix

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
